### ISSUE TITLE
BUG: 'output buffer too short' in WalletConnectSharp.Crypto\Crypto.cs

### ISSUE THREAD

**Issue by Blackcode** [WalletConnect/WalletConnectSharp#105]
The temp buffer fixed size of 8024 bytes throws error 'output buffer too short' in case the deserialized string exceeds that value. 
I have fixed that on my project by adding a variable buffer length **byte[] temp = new byte[@sealed.Length];**

Check my pull request https://github.com/WalletConnect/WalletConnectSharp/pull/104.

The faulty code is here:

[Core Modules\WalletConnectSharp.Crypto\Crypto.cs - Line 647](https://github.com/WalletConnect/WalletConnectSharp/blob/054926ea9a46acfe97eb2483d11fdb81f57d6870/Core%20Modules/WalletConnectSharp.Crypto/Crypto.cs#L643)

```
private string DeserializeAndDecrypt(string symKey, string encoded)
        {
            var param = Deserialize(encoded);
            var @sealed = param.Sealed;
            var iv = param.Iv;
            var type = int.Parse(Bases.Base10.Encode(param.Type));
            var isType1 = type == TYPE_1;
            
            var aead = new ChaCha20Poly1305();
            aead.Init(false, new ParametersWithIV(new KeyParameter(symKey.HexToByteArray()), iv));

            using MemoryStream rawDecrypted = new MemoryStream();
            byte[] temp = new byte[8024];
            int len = aead.ProcessBytes(@sealed, 0, @sealed.Length, temp, 0);
            
            if (len > 0)
            {
                rawDecrypted.Write(temp, 0, len);
            }

            len = aead.DoFinal(temp, 0);

            if (len > 0)
            {
                rawDecrypted.Write(temp, 0, len);
            }
                
            return Encoding.UTF8.GetString(rawDecrypted.ToArray());
        }
```

**Comment by gigajuwels** [comment]
This has been fixed in[ 2.0.6](https://github.com/WalletConnect/WalletConnectSharp/releases/tag/v2.0.6)
