### ISSUE TITLE
Approval Task is not called

### ISSUE THREAD

**Issue by yara73** [WalletConnect/WalletConnectSharp#107]
Greetings! I am using WalletConnect for Unity and couldn`t receive response from Approval task after connection was approved by the wallet.  Also I have been tried your sample from the wiki on repo page and result is the same.

`        
        var dappOptions = new SignClientOptions()
        {
            ProjectId = "39f3dc0a2c604ec9885799f9fc5feb7c",
            Metadata = new Metadata()
            {
                Description = "An example dapp to showcase WalletConnectSharpv2",
                Icons = new[] { "https://walletconnect.com/meta/favicon.ico" },
                Name = "WalletConnectSharpv2 Dapp Example",
                Url = "https://walletconnect.com"
            },
            // Uncomment to disable persistant storage
            // Storage = new InMemoryStorage()
        };
        
        var dappConnectOptions = new ConnectOptions()
        {
            RequiredNamespaces = new RequiredNamespaces()
            {
                {
                    "eip155", new RequiredNamespace()
                    {
                        Methods = new[]
                        {
                            "eth_sendTransaction",
                            "eth_signTransaction",
                            "eth_sign",
                            "personal_sign",
                            "eth_signTypedData",
                        },
                        Chains = new[]
                        {
                            "eip155:1"
                        },
                        Events = new[]
                        {
                            "chainChanged",
                            "accountsChanged",
                        }
                    }
                }
            }
        };
        
        var dappClient = await WalletConnectSignClient.Init(dappOptions);
        var connectData = await dappClient.Connect(dappConnectOptions);
        
        var sessionConnectTask = connectData.Approval;
        var sessionData = await sessionConnectTask;
`
sessionConnectTask is never awaited and i couldn`t get wallet to continue development. Can you help me ? Also i`ve been looking into your sources and specific event "session_connect" is never raised, so it could be possibly a bug or i am doing something wrong. Btw i used private project id also in case this functionality is restricted for the demo projectId

**Comment by Blackcode** [comment]
Try removing the events.

See if something could help you from my project. I'm doing a dapp Chia Wallet Connect.
https://github.com/Blackcode/ChiaWalletConnect.dotnet

**Comment by gigajuwels** [comment]
This has been fixed in[ 2.0.6](https://github.com/WalletConnect/WalletConnectSharp/releases/tag/v2.0.6)

**Comment by gigajuwels** [comment]
This has been fixed in[ 2.0.6](https://github.com/WalletConnect/WalletConnectSharp/releases/tag/v2.0.6)
