### ISSUE TITLE
2.0.6 WalletConnect.Sign "Invalid Session Properties requested"

### ISSUE THREAD

**Issue by VR-Innovations** [WalletConnect/WalletConnectSharp#115]
In the documentation you've to use **RequiredNamespace** to create the ConnectOptions, 2.0.6 uses **ProposedNamespace** instead. This throws the next error "Invalid Session Properties requested" while awaiting for the Approval. Fix for now is downgrading WalletConnetSign.

**Example - WalletConnetSign 2.0.6;**

dappConnectOptions = new ConnectOptions()
            .RequireNamespace("eip155", new **ProposedNamespace**()
                .WithMethod("eth_sendTransaction")
                .WithMethod("eth_signTransaction")
                .WithMethod("eth_sign")
                .WithMethod("personal_sign")
                .WithMethod("eth_signTypedData")
                .WithChain("eip155:1")
                .WithEvent("chainChanged")
                .WithEvent("accountsChanged"));

dappClient = await WalletConnectSignClient.Init(dappOptions);
connectData = await dappClient.Connect(dappConnectOptions);

GenerateQrCode(connectData.Uri);
deeplink = connectData.Uri;

WalletGenerated();

await connectData.Approval;

**throws @ connectData.Approval :**

**"Invalid Session Properties requested"**

**Example - WalletConnetSign 2.0.5;**

dappConnectOptions = new ConnectOptions()
            .RequireNamespace("eip155", new **RequiredNamespace**()
                .WithMethod("eth_sendTransaction")
                .WithMethod("eth_signTransaction")
                .WithMethod("eth_sign")
                .WithMethod("personal_sign")
                .WithMethod("eth_signTypedData")
                .WithChain("eip155:1")
                .WithEvent("chainChanged")
                .WithEvent("accountsChanged"));

dappClient = await WalletConnectSignClient.Init(dappOptions);
connectData = await dappClient.Connect(dappConnectOptions);

GenerateQrCode(connectData.Uri);
deeplink = connectData.Uri;

WalletGenerated();

await connectData.Approval;

**Succeeds**
            
 
Fix for now is downgrading to 2.0.5

**Comment by gigajuwels** [comment]
Can you confirm which wallet you are trying to connect to? I've been seeing wallets implement session properties in different ways

**Comment by VR-Innovations** [comment]
Updates to 2.1.0 and it does not have this problem anymore. I was connecting with Trust Wallet.

Also seem to have the issue that after some minutes, the await Approval does not get awaited/called?

**Comment by gigajuwels** [comment]
Can you open up a new issue for what you're describing in the last sentence? Just to keep things more organized and to get more details so I can fix it. Thank you!
