### ISSUE TITLE
TimeoutException: socket stalled

### ISSUE THREAD

**Issue by DayLingxiaozhou** [WalletConnect/WalletConnectSharp#119]
![image](https://github.com/WalletConnect/WalletConnectSharp/assets/47055239/afd23267-06f4-45a3-ac76-3294638ec67d)
![image](https://github.com/WalletConnect/WalletConnectSharp/assets/47055239/723bf3e0-46d8-4177-a67a-030cde4eda62)

 If the official website application project is not completely passed, will it cause the wss connection to fail？

**Comment by glitch-txs** [comment]
Hi, you don't need to verify your domain for C#/Unity use cases.
