### ISSUE TITLE
TypedData with BigInteger/uint256 Param Which Exceeds 16 Characters Does Not Prompt for Signature

### ISSUE THREAD

**Issue by underclockeddev** [WalletConnect/WalletConnectSharp#135]
Crossposting from WalletConnectUnity issue because I'm not sure this issue is Unity specific. original: https://github.com/WalletConnect/WalletConnectUnity/issues/109

Running into a weird issue now where if a BigInteger/uint256 in the TypedData is more than 16 digits long, MetaMask will not prompt me for the signature. But if I drop down to 16 or fewer digits, it will prompt me for the signature. I did try making those "99..." literals strings and using BigInteger.Parse("99....") and the outcome was the same, did not get a prompt when it was >16 digits

ps. I'm using the Permit from Nethereum.ABI.EIP712.EIP2612

![image](https://github.com/WalletConnect/WalletConnectSharp/assets/71031886/8dabd474-dc94-4395-bfe4-28365a06ab77)

**Comment by underclockeddev** [comment]
Also - let me know if you want me to make this a separate issue - when I do the call with Value = 9999999999999999 (18 9's) the popup on MetaMask rounds it up to 10000000000000000 (1 followed by 18 0's)
![image](https://github.com/WalletConnect/WalletConnectSharp/assets/71031886/5cbe25dd-8aa7-4895-98f9-dbdc66478ac5)

 
This definitely doesn't seem right

![image](https://github.com/WalletConnect/WalletConnectSharp/assets/71031886/78b21f49-c4e2-4e13-a68a-ee6f679305d2)
It doesn't seem as if the rounding is occurring before being sent to the wallet

**Comment by underclockeddev** [comment]
I threw a breakpoint in the Nethereum code on the WalletConnectClient.Request call and it seems that Nethereum is passing in the proper values. The only thing changing between typedData with 16-or-fewer digits and 17+ digits is the message.value property value, as expected. 

```
{
  "types": {
    "EIP712Domain": [
      {
        "name": "name",
        "type": "string"
      },
      {
        "name": "version",
        "type": "string"
      },
      {
        "name": "chainId",
        "type": "uint256"
      },
      {
        "name": "verifyingContract",
        "type": "address"
      }
    ],
    "Permit": [
      {
        "name": "owner",
        "type": "address"
      },
      {
        "name": "spender",
        "type": "address"
      },
      {
        "name": "value",
        "type": "uint256"
      },
      {
        "name": "nonce",
        "type": "uint256"
      },
      {
        "name": "deadline",
        "type": "uint256"
      }
    ]
  },
  "primaryType": "Permit",
  "domain": {
    "name": "DWG",
    "version": "1",
    "chainId": 80001,
    "verifyingContract": "0xRedacted"
  },
  "message": {
    "owner": "0xRedacted",
    "spender": "0xRedacted",
    "value": 2500000000000000000,
    "nonce": 1,
    "deadline": 1
  }
} 
```

**Comment by underclockeddev** [comment]
Ok, so I'm actually able to just change the Permit.Value `type` to string and everything just works. I think this is a workaround and not a fix, so I'm going to leave this issue open in case you guys want to do some digging and see what's causing the arbitrary digit limit on BigInts.

**Comment by skibitsky** [comment]
Hey @charlesteets,

Thank you for updating the issue!

Have you tried using other wallets to see if the same problem persists?

Do you use `eth_signTypedData` or `eth_signTypedData_v4`?

**Comment by underclockeddev** [comment]
I have not. I'm assuming a majority of my users will be using MetaMask so that's all I've been using for testing my app. 

I use v4

**Comment by glitch-txs** [comment]
Just tested this on the web side and it seems to be an issue on the MetaMask side.
I tested with your parameters, it works well in other wallets, in MetaMask it does nothing unless I change the value as you stated.

I would suggest testing with other wallets like Trust Wallet, this helps us scope the issue and know if the problem is in the library or the wallet side.

I would suggest opening an issue in the MetaMask mobile repository since this is not related to Unity/C# implementation. Thanks for reporting! 🤝 

https://github.com/MetaMask/metamask-mobile

**Comment by underclockeddev** [comment]
Thanks for looking into this more!
