### ISSUE TITLE
Sign Api question 

### ISSUE THREAD

**Issue by fridstein** [WalletConnect/WalletConnectSharp#143]
Hello! I am trying to make a c# wallet based on nethereum and while i successfully managed to connect to any website with my account, i dont understand how to receive the evnts from dapp, for example dapp wants me to sign a simple message or typed message after and i dont understand how to make it, can you help please, because as i understand auth api is not for these needs. Thank you in advance

**Comment by fridstein** [comment]
i also was trying different methods from sdk documentation, but some of them doesnt work at all :(

**Comment by skibitsky** [comment]
Hey @fridstein,

If you want to sign custom messages, transactions, etc, you should use Sign API instead.
