### ISSUE TITLE
Unity Project can't connect wallet

### ISSUE THREAD

**Issue by SYLing** [WalletConnect/WalletConnectSharp#15]
wc:ddd77acc-1085-4c61-bb60-eaebe7bb0592@1?bridge=wss%3A%2F%2Fbridge.walletconnect.org&key=20b713e41343c96815aec71e2e2a9a9d9ac47d2a0832e725853fc8115a988bfe
UnityEngine.Debug:Log(Object)
<Start>d__0:MoveNext() (at Assets/TestWalletConnect.cs:13)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start(<Start>d__0&)
TestWalletConnect:Start()

Connection Open!
UnityEngine.Debug:Log(Object)
WalletConnectSharp.Unity.Network.NativeWebSocketTransport:<Open>b__11_0() (at Assets/WalletConnectSharp/WalletConnectSharp.Unity/Network/NativeWebSocketTransport.cs:54)
NativeWebSocket.<Connect>d__26:MoveNext() (at Assets/WalletConnectSharp/WalletConnectSharp.Unity/Network/Client/NativeWebSocket.cs:512)
UnityEngine.UnitySynchronizationContext:ExecuteTasks() (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)

the code 

       var walletConnectManager = this.GetComponent<WalletConnectManager>();

        Debug.Log(walletConnectManager.ConnectURL);

        await walletConnectManager.Provider.Connect();

        Debug.Log("The account " + walletConnectManager.Provider.Accounts[0] + " has connected!");

**Comment by SYLing** [comment]
imtoken scan qrcode alert : "Missing or invaild topic field"

**Comment by SYLing** [comment]
wc:ab396d68-1238-4662-aca7-e0e0e0a42e70@1?bridge=wss%3A%2F%2Fbridge.walletconnect.org&key=f143a0d75156da6b7fa69c9f9198a74a6b9f36369b361a88a4850068bb0314c2
Adding JsonRpcResponse callback to event response:1626941605952585
Subscribing Event Provider to response:1626941605952585
Adding listener to EventProvider list. New count: 1
Adding GenericEvent callback to event connect
Subscribing Event Provider to connect
Adding listener to EventProvider list. New count: 1
Adding GenericEvent callback to event session_failed
Subscribing Event Provider to session_failed
Adding listener to EventProvider list. New count: 1



There is a certain probability of successful connection, and the connection can be successful only by using imtoken. Tokenpocket, mathwallet and trust wallet cannot be connected successfully. What is the reason.

**Comment by Graciela985** [comment]
It's an issue with some wallets apparently.I had a similar issue. I contacted metamask/binance directly and they had it resolved for me. alarcongraciela985@gmail.com
Send them a mail. They'll help you out.

**Comment by gigajuwels** [comment]
this is a v1 issue.
