### ISSUE TITLE
Upgrade Nethereum Dependencies to 4.0.x

### ISSUE THREAD

**Issue by gcbsumid** [WalletConnect/WalletConnectSharp#17]
Nethereum recently released a new version that includes upgrades for EIP1559. The existing version of WalletConnectSharp (0.1v) is linked to 3.8.0.0 (PublicKeyToken=8768a594786aba4e) 

A couple of things:
1. Nethereum's dependency is to Nethereum.JsonRPC.Client.dll 4.0.0.0 whereas WalletConnectSharp's dependency is to 3.8.0.0
2. The version of Nethereum's dlls that WalletConnect requires the specific dlls that are signed with PublicKeyToken=8768a594786aba4e, whereas I'm using NEthereum net461dllsAOT.4.0.5 which has their dlls not signed with a public key token (PublicKeyToken=null). They do not match and unity doesn't allow 2 dlls with the same name and so WalletConnect doesn't recognize it.

Code sample:
`            var provider = mWalletConnect.CreateProvider(new Uri(uri));

            return new Web3(provider);
`
The first line [walletconnect.createProvider()] requires Nethereum.JsonRPC.Client.dll 3.8.0.0 
but the second line [new Web3(provider)] requires Nethereum.JsonRPC.Client.dll 4.0.0.0 

Please release a new nuget version that links to the newer version of Nethereum. Thanks

**Comment by john-s-morgan** [comment]
Currently targeting 4.4.1. Is this still an issue?
