### ISSUE TITLE
Ui missing walletConnectModel Prefab

### ISSUE THREAD

**Issue by AzharKhemta** [WalletConnect/WalletConnectSharp#180]
I import this pickage    and add prefab in  scene but showing missing ui  please give me solution
![missing](https://github.com/WalletConnect/WalletConnectSharp/assets/98034379/d913c822-a308-4f19-8a63-969157b7bdbb)

**Comment by skibitsky** [comment]
Hey @Kheemta,

This is the WalletConnectSharp repository. The modal and Unity core package are part of WalletConnectUnity. Please follow [the instructions in the documentation](https://docs.walletconnect.com/advanced/walletconnectmodal/about?platform=unity) to import the modal package. If the issue continues, kindly open a new issue in the WalletConnectUnity repository.
