### ISSUE TITLE
Support for WalletConnect V2

### ISSUE THREAD

**Issue by monkjuice** [WalletConnect/WalletConnectSharp#19]
Are there plans on supporting the V2 of the protocol with this library?

I would be glad to help if needed.

Regards

**Comment by SubbaKerl** [comment]
I wouldn't want to second monkjuice's comment.

Any feedback so far? Is this package still actively developed/enhanced?

**Comment by ecp4224** [comment]
This package is still being actively developed by myself. I have started on support for v2 however I've been bogged down by other projects and the workload required to catch up to v2

Will update here with an experimental branch once it's ready for public release

**Comment by Hobbs1210** [comment]
any update on this ?

**Comment by ecp4224** [comment]
An alpha version of the v2 Sign client has been open sourced here:

# [WalletConnectSharp v2](https://github.com/gigajuwels/WalletConnectSharpV2)

## Please Note

1. This library is in alpha. The current API matches the Typescript library very tightly. This may change in the offical Nuget release with some APIs being replaced with a more C# friendly equivalent. 
2. This repo will be moved under WalletConnect org before Nuget release. Consider this a "pre-release" on nuget
3. The package will be released on nuget (and repo moved) in early December. We are finalizing the documentation and unit tests.

**Comment by gigajuwels** [comment]
V2 is now public in the [2.0 branch ](https://github.com/WalletConnect/WalletConnectSharp/tree/2.0)
