### ISSUE TITLE
Working example please

### ISSUE THREAD

**Issue by aliveli186** [WalletConnect/WalletConnectSharp#2]
Could you please add a working example.
I tried the code with MetaMask which fails silently and TrustWallet which says "An unknown error occured." and stalls in "Connecting..." phase.

**Comment by numerized** [comment]
Would be awesome, I'll create a youtube video to set this into a unity project as well

**Comment by m1guelpf** [comment]
@numerized Would love to get an example Unity starter project with this library and Nethereum!

**Comment by Skyrac** [comment]
Hey there, any updates here?
Tried to run the example but it throws an error on connect.

Also tried to convert the version for Unit. Meta Mask Pops up but no connection request is made (where you can agree or reject). Trust wallet also pops an unknown error message.

**Comment by testsellpixels** [comment]
the current example doesn't work, calling ex: var walletConnectData = await walletConnect.Connect(); just hangs.
Is there anything besides doing steps 1-4 that will work. I tried the Netherium console example and attempted to integrate into a blazor server, but it hangs exactly the same.

Any help would be appreciated, if you like I can write up a tutorial once I get it working locally
