### ISSUE TITLE
Please update nuget packages to actual version

### ISSUE THREAD

**Issue by RoboNET** [WalletConnect/WalletConnectSharp#20]
Current published version has few bugs with saved session

**Comment by ecp4224** [comment]
Thanks for making me aware of this, I've uploaded a new nuget package version (v1.6.6) which represents this [commit](https://github.com/WalletConnect/WalletConnectSharp/commit/2f06027bf1319aaa698444ae9d92256dd9856da9). This problem should be fixed now

**Comment by RoboNET** [comment]
Yes, problem fixed. Thanks!
