### ISSUE TITLE
When QR code is scanned after 60 seconds session response is not received

### ISSUE THREAD

**Issue by nottforestny** [WalletConnect/WalletConnectSharp#27]
I used sample code with latest 1.7.1 NuGet packages and latest source and in both versions everything works fine if QR code is scanned within 60 seconds, but if it's after 61 seconds or more, session response is not received.

This behavior is across blockchains - Ethereum, BSC, and across wallets - TrustWallet, MathWallet.

```
var metadata = new ClientMeta()
{
    Description = "This is a test of the Nethereum.WalletConnect feature",
    Icons = new[] {"https://app.warriders.com/favicon.ico"},
    Name = "WalletConnect Test",
    URL = "https://app.warriders.com"
};
var walletConnect = new WalletConnect(metadata);
var walletConnectData = await walletConnect.Connect();
```

By the way, seems that example dapp (not C#) https://example.walletconnect.org/ works fine even after 60 seconds.

**Comment by ecp4224** [comment]
A [hardcoded session connection timeout](https://github.com/WalletConnect/WalletConnectSharp/blob/main/WalletConnectSharp.Core/WalletConnectSession.cs#L210) of 2 minutes was introduced. It seems (at least at the time of the commit that added the timeout), that the relay server would not allow a session to connect if the session request was more than 2 minutes old. If this has changed, then this timeout can be made longer

**Comment by gigajuwels** [comment]
this has been fixed in v2
