### ISSUE TITLE
Create Unit Tests

### ISSUE THREAD

**Issue by ecp4224** [WalletConnect/WalletConnectSharp#4]
Create some unit tests to test basic functionality

**Comment by ef3n9r98** [comment]
Hi @ecp4224, I know some devs who'd be interested in working on this. Is there a budget for fixing this issue, and if so, how much? 

I'd put this issue up on [OpenQ](http://www.openq.dev/).

Thanks!

**Comment by gigajuwels** [comment]
we have unit tests now.
