### ISSUE TITLE
not working in second connection

### ISSUE THREAD

**Issue by SoftDev56** [WalletConnect/WalletConnectSharp#5]
I build this open source as nuget package and import into my project to use walletconnect. It worked fine at first time. But when try to connect second time, there is an error occurred. In other words, only working in first loading.

Issue in this line : var walletConnect = new WalletConnect(metadata);

System.InvalidOperationExceptionAn attempt was made to transition a task to a final state when it had already completed.

**Comment by edkek** [comment]
Could you provide a minimal example to reproduce this problem?
