### ISSUE TITLE
WalletSwitchEthChain not working. 

### ISSUE THREAD

**Issue by monkjuice** [WalletConnect/WalletConnectSharp#59]
Using the latest version of WalletConnect, Nethereum and net 6.0.

Also tried intializing walletconnect both using the 'old way' and through `BuildWeb3`. Also tried both unnmanaged and AsWalletAccount.

The error looks as following;

`System.ArgumentNullException: 'Value cannot be null. (Parameter 'key')'`

Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.9\System.Private.CoreLib.dll

call stack:
![image](https://user-images.githubusercontent.com/20531817/195786380-0e1dda7b-2ab5-4f98-ab0d-30ea721d876d.png)

the code: 
![image](https://user-images.githubusercontent.com/20531817/195786783-1aeeea34-f22e-4d64-a264-d96dec6eed22.png)

**Comment by gigajuwels** [comment]
this is a v1 issue, wont fix
