### ISSUE TITLE
WalletConnect V2 nuget package not available

### ISSUE THREAD

**Issue by axenteoctavian** [WalletConnect/WalletConnectSharp#67]
Hello @gigajuwels!

The NuGet package is not available to install.

`dotnet add package WalletConnect.Sign` not working

Thank you!

**Comment by faceoffers28** [comment]
@axenteoctavian Same here. I had to download the code. I then built the solution and imported the existing project (WalletConnectSharp.Sign) into my existing solution.

**Comment by gigajuwels** [comment]
These packages have been pushed to [nuget](https://www.nuget.org/packages/WalletConnect.Sign). Please make sure to use version `2.0.3`
