### ISSUE TITLE
WalletConnect V2 conversion not working for MessageEvent

### ISSUE THREAD

**Issue by axenteoctavian** [WalletConnect/WalletConnectSharp#68]
Hello @gigajuwels!

I'm trying to use the wallet connect v2 in my application but I get this error:
![image](https://user-images.githubusercontent.com/45915201/215093275-b443a009-c881-4496-b5da-634cb805defd.png)

Do you have any idea why it might not work? 
Thank you!

**Comment by gigajuwels** [comment]
This issue has been fixed in the latest commit in v2 branch
