### ISSUE TITLE
Nethereum extensions on walletconnect V2

### ISSUE THREAD

**Issue by monkjuice** [WalletConnect/WalletConnectSharp#69]
Hi.

We are using Walletconnect + Nethereum for our infrastructure. I'm taking a look at the code but it looks like its no longer possible to return an object of type Nethereum IClient when creating a new provider.

We really depend on this to continue working.

Thanks in advance,

Agu

**Comment by GrahamMcBain** [comment]
Hey @monkjuice check out the V2 branch!

https://github.com/WalletConnect/WalletConnectSharp/tree/2.0

**Comment by Dryec** [comment]
Looking forward to a Nethereum extension for V2! Any timeline available for this?

**Comment by skibitsky** [comment]
Nethereum now has [Nethereum.WalletConnect](https://www.nuget.org/packages/Nethereum.WalletConnect) package based on WalletConnectSharp v2.
