### ISSUE TITLE
Wallet example?

### ISSUE THREAD

**Issue by random-internet-guy** [WalletConnect/WalletConnectSharp#7]
Just wondering if an example will be published at some point on how to implement WalletConnect into build a custom wallet. I'm looking for information on how to digest the uri provided by a dapp and approving the session. An example that extends past that would be a bonus. This would be helpful for people looking to get started on implementing custom wallets in C# as the official documentation seems to be lacking.

Much appreciated

**Comment by edkek** [comment]
So this library currently only supports the other way around (acting as a dapp connecting to a wallet). However, I think it'd be a great idea to support both sides of the transaction :) 

I've created task #11 for this

**Comment by ecp4224** [comment]
This will be coming with v2

**Comment by ecp4224** [comment]
I'm reopening this issue to target the 1.8 release.
A new branch has been started to support this here:
https://github.com/WalletConnect/WalletConnectSharp/blob/feat/wallet/Examples/console/Examples/BiDirectionalExample.cs

**Comment by gigajuwels** [comment]
this is supported in v2 now
