### ISSUE TITLE
Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path '['wc@2:core:0.3//WalletConnectSharpv2 Dapp

### ISSUE THREAD

**Issue by faceoffers28** [WalletConnect/WalletConnectSharp#70]
Here is the error message.

Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path '['wc@2:core:0.3//WalletConnectSharpv2 Dapp Example-client-core-messages'].SOMEBIG LONGCHARACTERSTRING', line 1, position 12285.

If you run the code in the ReadMe, it fails in the following line. 

 `var dappClient = await WalletConnectSignClient.Init(dappOptions);`

Here is the file.

`WalletConnectSignClient.cs. `

This is the method.

`WalletConnectSignClient(SignClientOptions options)
`

Here is my csproj.

```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net6.0</TargetFrameworks>
        <PackageVersion>2.0.0-rc.1</PackageVersion>
        <AssemblyVersion>2.0.0</AssemblyVersion>
        <FileVersion>2.0.0</FileVersion>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <Title>DDWalletConnectSharp.Sign</Title>
        <Description>DD create nuget package for WalletConnect Sign.</Description>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\WalletConnectSharp.Core\WalletConnectSharp.Core.csproj" />
    </ItemGroup>

</Project>
```

**Comment by Blackcode** [comment]
It happens because your store.json got corrupted.

Go to `C:\Users\YOURUSERNAME\.wc` and delete **store.json**.

Another solution would be adding **Storage = new InMemoryStorage()** in your SignClientOptions() initializer
