### ISSUE TITLE
Nuget installation failure: No versions available for package 'WalletConnect.Sign'

### ISSUE THREAD

**Issue by memewizards** [WalletConnect/WalletConnectSharp#71]
There are no versions available for the package 'WalletConnect.Sign'.

  Writing C:\Users\example\exampleproject
info : X.509 certificate chain validation will use the default trust store selected by .NET.
info : Adding PackageReference for package 'WalletConnect.Sign' into project 'C:\Users\example\exampleproject.csproj'.
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/walletconnect.sign/index.json
info :   NotFound https://api.nuget.org/v3/registration5-gz-semver2/walletconnect.sign/index.json 91ms
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/walletconnect.sign/index.json
info :   NotFound https://api.nuget.org/v3/registration5-gz-semver2/walletconnect.sign/index.json 275ms
error: There are no versions available for the package 'WalletConnect.Sign'.

**Comment by faceoffers28** [comment]
I had to download the code. I then built the solution and imported the existing project (WalletConnectSharp.Sign) into my existing solution.

**Comment by gigajuwels** [comment]
These packages have been pushed to [nuget](https://www.nuget.org/packages/WalletConnect.Sign). Please make sure to use version `2.0.3`
