### ISSUE TITLE
Any plans to incorporate the Auth API?

### ISSUE THREAD

**Issue by Luzzotica** [WalletConnect/WalletConnectSharp#72]
I'm building a game, and would love to authenticate users using their wallets.

In order to do that, I need the Auth API for wallet connect working.

What's time timeline to getting that added to this repo?

**Comment by gigajuwels** [comment]
Hi @Luzzotica 
Our current timeline is to have the AUTH API ready to go before April.

**Comment by gigajuwels** [comment]
[WalletConnect.Auth ](https://www.nuget.org/packages/WalletConnect.Auth)has been released on nuget
