### ISSUE TITLE
How to transaction the USDT in PolyGon and BSC network other than matic and bnb in V1 or v2?

### ISSUE THREAD

**Issue by flyarong** [WalletConnect/WalletConnectSharp#74]
Thanks.

**Comment by skibitsky** [comment]
@flyarong

You need to call functions on ERC20 contracts of USDT. We have a sample for the Unity SDK which is based on WalletConnectSharp, you can use it for reference.

https://docs.walletconnect.com/advanced/walletconnectmodal/usage?platform=unity#interaction-with-smart-contracts
