### ISSUE TITLE
Resuming sessions example

### ISSUE THREAD

**Issue by m1guelpf** [WalletConnect/WalletConnectSharp#8]
Many other clients include the ability to export the current session for storage and to resume a stored session.

I've looked into how this is implemented on the [Swift client](https://github.com/WalletConnect/WalletConnectSwift), and it seems we'd need to store the list of accounts and the chainID (as those are only returned on the first connection), plus the peerID of the wallet and our dApp (we might also have to store our key, although the Swift client doesn't seem to do it).

Then, we should initiate the WebSocket connection (and propagate all the data from the session into the client), and we should be ready to go. I'm planning to try building an implementation of this, but I've never written any C# so I'd really appreciate some help 😁

**Comment by edkek** [comment]
Created a task for this at #9 for serialization/deserialization functionality

**Comment by ecp4224** [comment]
This task has been completed a while ago, closing issue now with following example:

```csharp
// Create WalletConnectSession object or equivalent
var session = new WalletConnectSession(....);
// Connect session normally
await client.Connect();

// Grab the session data as a SavedSession object
var sessionData = client.SaveSession();
// Convert object to json
var json = JsonConvert.SerializeObject(sessionData);

// ... Write to disk, maybe store encrypted or something ...

// Convert the json back to a SavedSession object
var storedSessionData = JsonConvert.DeserializeObject<SavedSession>(json);

// Resume the session by creating a new instance passing in the SavedSession object
var resumedSession = new WalletConnect(storedSessionData);
// And connect the session
await resumedSession.Connect();
```
