### ISSUE TITLE
Unable to authenticate wallet in unity 

### ISSUE THREAD

**Issue by Sushmita1301** [WalletConnect/WalletConnectSharp#89]
1.After confirming my wallet authorization in metamask app, the wallet address is not taken by the app. This step fails to authenticate the wallet for the latest 6.5.0 metamask app.
2.It seems to work fine for the older version of metamask app (v6.3.0)
3.I have used all the alphanumerical subdomains of the bridge url such as "f.bridge.walletconnect.org", "m.bridge.walletconnect.org", "8.bridge.walletconnect.org", etc.
It doesn't seem to work on android either for me. Are there any updates or suggestions to where might the problem occur and how I can fix it?

**Comment by gigajuwels** [comment]
this is a v1 issue, and v1 is not longer supported.
