### ISSUE TITLE
Save + Resume Session

### ISSUE THREAD

**Issue by ecp4224** [WalletConnect/WalletConnectSharp#9]
We should offer a way to save sessions and resume sessions. 

There should be an added function in the `WalletConnect` class that will write the session data to a given stream. The function should make no assumptions about how the save will occur, it should simply write to a stream given

```
public virtual void WriteSession(System.IO.Stream stream)
```

To resume a session, the `WalletConnect` class should offer a constructor with only a `System.IO.Stream` variable that will be used to read in the session data. This should be the reverse of `WriteSession`

**Comment by lej333** [comment]
When you will finalize this? I see there is a pull request but not merged yet
