### ISSUE TITLE
Nethereum integration of Requests / Responses

### ISSUE THREAD

**Issue by juanfranblanco** [WalletConnect/WalletConnectSharp#94]
Hi!

I am Juan Blanco from https://github.com/Nethereum/Nethereum, I am in the process to create a wallet connect package similar to the https://github.com/Nethereum/Nethereum/tree/master/src/Nethereum.Metamask, so far (architecture wise :) ) so good, as I will be creating and interceptor for:
```
 "eth_sendTransaction",
  "eth_signTransaction",
  "eth_sign",
  "personal_sign",
  "eth_signTypedData",
```

Now I am stuck creating the mapping objects for the Request / Response, and I don't know if I should craft myself something bypassing these and calling directly, as they are the standard rpc objects (no?)

```
  id[0] = await MessageHandler.SendRequest<SessionRequest<T>, TR>(topic, new SessionRequest<T>()
            {
                ChainId = defaultChainId,
                Request = request
            });
```

What I have tried so far is to create these mapping objects, but I assume this might be incorrect as I cannot see where the serialisation is taking place.

```

    [RpcMethod("eth_sendTransaction"), RpcRequestOptions(Clock.ONE_MINUTE, 99998)]
    public class WCEthSendTransactionRequest
    {
        public TransactionInput TransactionInput { get; set; }
    }

    [RpcResponseOptions(Clock.ONE_MINUTE, 99999)]
    public class WCEthSendTransactionResponse
    {
        public string TransactionHash;
    }
```

**Comment by axenteoctavian** [comment]
Maybe this will help you 😃

https://github.com/WalletConnect/WalletConnectSharp/issues/92#issuecomment-1569067536

**Comment by juanfranblanco** [comment]
Thanks @axenteoctavian, still stucked as I need the right signature for wc, ill keep trying variations :)

**Comment by fudgebucket27** [comment]
@juanfranblanco Have you got personal_sign working and do you have an example I could look at please?

**Comment by monkjuice** [comment]
Hey! We really depend on Nethereum + WalletConnect on our dapp. Which is being actively used by dozens of developers.

Any updates on this?

Thanks

**Comment by OpenMetaAleissia** [comment]
Any update on this?

**Comment by gigajuwels** [comment]
The rpc request classes built for `SendRequest`must match the [param](https://docs.ethermint.zone/basics/json_rpc.html#eth-sendtransaction) field type for the given method. For example, for `eth_sendTransaction`, you would need to make `WCEthSendTransactionRequest` a `List<TransactionInput>`

You can view an example [here](https://github.com/WalletConnect/WalletConnectUnity/blob/2.0/Assets/WalletConnectUnity/Demo/SimpleSign/Scripts/DemoDapp.cs#L53)

**Comment by juanfranblanco** [comment]
Thanks @gigajuwels I missed your response ill try it!
Edit: Working now :) great example.
