### ISSUE TITLE
Bug: How to reuse an aproved connection

### ISSUE THREAD

**Issue by Blackcode** [WalletConnect/WalletConnectSharp#95]
How to connect to an already aproved connection? I am connecting to Chia blockchain.
I have problem using this library due to lack of examples.

Thanks in advance.

Update: it happens randomly.

```
    public class WalletConnectService
    {
      public async Task ReConnect()
              {
                  var options = new SignClientOptions()
                  {
                      ProjectId = "a97dbb2756d03b9160843f6ec3ecb989",
                      Metadata = new Metadata()
                      {
                          Description = "Chia Connect",
                          Icons = new[] { "https://s2.coinmarketcap.com/static/img/coins/200x200/9258.png" },
                          Name = "ChiaConnect",
                          Url = "https://chia.org/",
                      },
                      //Storage = new InMemoryStorage()
                  };
                  var client = await WalletConnectSignClient.Init(options);
      
                  try
                  {
                      var data = new WalletsRequest("1921498453", false);
                      var response = await client.Request<WalletsRequest, dynamic>("topic, data);
                  }
                  catch (Exception ex)
                  {
                      Console.WriteLine(ex);
                  }
              }
}
[RpcMethod("chia_getWallets")]
    public class WalletsRequest
    {
        public string fingerprint { get; set; }
        public bool includeData { get; set; }
        public WalletsRequest(string fingerprint, bool includeData)
        {
            this.fingerprint = fingerprint;
            this.includeData = includeData;
        }
    }
```

**Comment by Blackcode** [comment]
Found what was happening. I think the library is broken.
In case of a reconect the request is actualy waiting for the session Key (Client.Session.Keys) and not the Topic.

Engine.cs
if (!this.**Client.Session.Keys.Contains**(topic))
                throw WalletConnectException.FromType(ErrorType.NO_MATCHING_KEY,
                    $"session topic doesn't exist {topic}");

**Comment by axenteoctavian** [comment]
You do not have the `topic` to make the request.
Something like this might work:
```csharp
var client = await WalletConnectSignClient.Init(options);
if(client.Find(options.RequiredNamespaces).Length > 0)
{ 
  //session is available
  var sessionData = _client.Find(_dappConnectOptions.RequiredNamespaces)[0];
  //OR var sessionData = _client.Find(_dappConnectOptions.RequiredNamespaces).Where(x => x...).First();
  
  try
  {
      var data = new WalletsRequest("1921498453", false);
      var response = await client.Request<WalletsRequest, dynamic>(sessionData.Topic, data);
  }
  catch (Exception ex)
  {
      Console.WriteLine(ex);
  }
}
else
{
  //session not available
}
```

**Comment by Blackcode** [comment]
@axenteoctavian actually I had the topic right (the posted code was the wrong one)

The real problem is actually maintaining the session. Randomly it creates a 0 bytes files in C:\Users\edrag\.wc\store.json. I have some hacky code to fix that.
You can check my project here, it's still in wip. https://github.com/Blackcode/ChiaWalletConnect.dotnet

**Comment by axenteoctavian** [comment]
I also encountered the bug with file with 0 length but I don't know the reason. Also sometimes the lib will crash and will broke the file and will not work unless you delete the file and reopen the app.

I thought you want to reuse the session from the file if it's valid since last usage. So I send you the code that will "find" the session, not going through "approve" process.
