### ISSUE TITLE
How to Sign a Message?

### ISSUE THREAD

**Issue by fudgebucket27** [WalletConnect/WalletConnectSharp#97]
How do you sign a message using "personal_sign"? I can't seem to find any examples in the repo at all? I'm guessing the ".Approve" method is involved somehow?

**Comment by axenteoctavian** [comment]
https://github.com/WalletConnect/WalletConnectSharp/issues/92#issuecomment-1569067536

**Comment by fudgebucket27** [comment]
Thanks for that. I'm trying with the following:

```csharp
    [RpcMethod("personal_sign")]
    public class WalletConnectPersonalSignRequest
    {
        public string message { get; set; }
        public string account { get; set; }
        public WalletConnectPersonalSignRequest(string message, string account )
        {
            this.message = message;
            this.account = account;
        }
    }
  ```
  
  Usage:
```csharp
   var request = new WalletConnectPersonalSignRequest(message, accountAddress);
    var response = await client.Request<WalletConnectPersonalSignRequest, dynamic>(sessionData.Topic, request);
```
The message to approve the signing doesnt pop up in my wallet though. What am I doing wrong?

**Comment by dpradell-dev** [comment]
@axenteoctavian @fudgebucket27 subscribing to your issue. Any idea what we're doing wrong?

**Comment by fudgebucket27** [comment]
Figured it out thanks to this comment in this issue: https://github.com/WalletConnect/WalletConnectUnity/issues/74#issuecomment-1698368015
